// Code generated by mockery. DO NOT EDIT.
// Source: users-service/internal/connector/google (interfaces: Client)

package mocks

import (
	context "context"

	google "users-service/internal/connector/google"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

func (m *Client) ExchangeCodeToToken(ctx context.Context, req google.ExchangeCodeToTokenRequest) (*google.ExchangeCodeToTokenResponse, error) {
	args := m.Called(ctx, req)
	var r0 *google.ExchangeCodeToTokenResponse
	if rf, ok := args.Get(0).(func(context.Context, google.ExchangeCodeToTokenRequest) *google.ExchangeCodeToTokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if args.Get(0) != nil {
			r0 = args.Get(0).(*google.ExchangeCodeToTokenResponse)
		}
	}

	var r1 error
	if rf, ok := args.Get(1).(func(context.Context, google.ExchangeCodeToTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = args.Error(1)
	}

	return r0, r1
}

